name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: main
